services:
  simulator:
    build: . 
    depends_on:
      - redis
    networks:
      - test
    deploy:
      replicas: 10  

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - test

networks:
  test:
    name: test
