services:
  simulator:
    build: ./sim
    depends_on:
      # - redis
      - rule-engine
      - rest-server
    networks:
      - test
    deploy:
      replicas: 5

  rule-engine:
    build: ./rule_engine
    networks:
      - test       
    environment:
      - HOST=rest-server

  rest-server:
    build: ./rest_server
    container_name: rest-server
    networks:
      - test
    ports:
      - "8000:8000"

  # redis:
  #   image: redis/redis-stack
  #   container_name: redis
  #   environment:
  #     - REDIS_URL=redis://default:ybaCdWLadAzqrb2qXO7QhKgjiDL3pXZ5@redis-16652.c212.ap-south-1-1.ec2.cloud.redislabs.com:16652
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001"
  #   networks:
  #     - test

  prometheus-sim:
    image: prom/prometheus
    container_name: prometheus-sim
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - test  

  # grafana-sim:
  #   image: grafana/grafana
  #   container_name: grafana-sim
  #   restart: unless-stopped
  #   ports:
  #    - '3001:3000'
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #   networks:
  #     - test  

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #   - 9000:8080
  #   volumes:
  #   - /:/rootfs:ro
  #   - /var/run:/var/run:rw
  #   - /sys:/sys:ro
  #   - /var/lib/docker/:/var/lib/docker:ro
  #   # for centos, fedora
  #   # - /cgroup:/cgroup:ro
  #   privileged: true
  #   depends_on:
  #   - redis    
  #   networks:
  #     - test

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ../ngrok/ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040    

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   ports:
  #     - 6969:9100
  #   networks:
  #     - test  

volumes:
  grafana-storage: {}
  prom_data:

networks:
  test:
    name: test